### ISSUE TITLE
Deprecate argument to lib_version()

### ISSUE THREAD

**Issue by pprindeville** [maxmind/geoip-api-perl#19]
I'm looking at:

```
const char *
lib_version(CLASS)
char * CLASS
```

in IP.xs and it's unclear why this function takes an argument since it's unused.  Indeed, it's highly likely that you'd want to check the version before instantiating an object, such as:

```
use version;

my $wanted = version->parse('v1.4.4');
my $have = version->parse(Geo::IP::lib_version());

my $gi;
if ($have >= $wanted) {
    $gi = Geo::IP::open_type(... opened the preferred way ...);
} else {
    $gi = Geo::IP::open_type(... opened the legacy way ...);
```

so it's not clear that the argument to lib_version() serves any purpose, and I think it can safely be deprecated.

Requiring the class for `$gi->lib_version()` seems to be putting the cart before the horse, as you'd have already instantiated `$gi` by then.

**Comment by oschwald** [comment]
I think it is intended to be used like `Geo::IP->lib_version`. You don't need to instantiate it.

**Comment by pprindeville** [comment]
Yeah, okay.  Just tried that and it works.
