### ISSUE TITLE
MYMETA should not be included

### ISSUE THREAD

**Issue by chorny** [maxmind/geoip-api-perl#23]
Your distribution (MAXMIND/Geo-IP-1.45.tar.gz) contains files MYMETA.yml and/or MYMETA.json. These files should not be included into distribution - they are generated when installing.
See http://weblog.bulknews.net/post/44251476706/stop-shipping-mymeta-to-cpan

P.S. If this report is about old version, please delete old indexed versions mentioned here: http://cpanold.chorny.net/?a=MAXMIND and contact me.

**Comment by oschwald** [comment]
Thanks for the report! We'll look into this.

**Comment by oalders** [comment]
Closed vi #26.  Thanks very much for reporting this. :)
