### ISSUE TITLE
name_by_addr_v6

### ISSUE THREAD

**Issue by eak** [maxmind/geoip-api-perl#28]
I am using Geo::IP 1.50 from CPAN. When I try to use name_by_addr_v6 I get
`Can't locate object method "name_by_addr_v6" via package "Geo::IP" at ...`
I looked at the source and I don't see any attempt to define the method. Am I missing something?

**Comment by oschwald** [comment]
It appears that it may only be defined if you are compiling it against `libGeoIP`.
